Changing autojudge scripts to show runtime error messages to teams.

diff --git a/doc/problemexamples/marathon/run/host b/doc/problemexamples/marathon/run/host
--- a/doc/problemexamples/marathon/run/host
+++ b/doc/problemexamples/marathon/run/host
@@ -111,25 +111,60 @@ cp "$1" run.exe 2>/dev/null
 
 file run.exe | grep -iq "statically linked"
 if [ "$?" != "0" ]; then
-  echo "Warning: $1 is not statically linked" >&2
+  echo "Warning: $1 is not statically linked"
 #  exit 47
 fi
 
 cdir=`pwd`
-echo "Current directory is $cdir -- chrooting on it" >&2
-echo "Running $sf to check execution" >&2
-echo "$sf -p -a -F11 -f$maxf -r1 -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe ----> NOT WORKING!!!! WHY!?!?!" >&2
-./run.exe <$cdir/stdin0 1>$cdir/stdout0 2>$cdir/stderr0
+echo "Current directory is $cdir -- chrooting on it"
+echo "Running $sf to check execution"
+echo "$sf -p -a -F11 -f$maxf -r1 -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe ----> NOT WORKING!!!! WHY!?!?!"
+
+printf -v int_time %.0f "$time"
+time = $((int_time + 1))
+
+cat <<EOF > runit.sh
+#!/bin/bash
+#http://stackoverflow.com/questions/687948/timeout-a-command-in-bash-without-unnecessary-delay
+(
+    ((t = $time))
+
+    while ((t > 0)); do
+        sleep 1
+        kill -0 \$\$ || exit 0
+        ((t -= 1))
+    done
+
+    # Be nice, post SIGTERM first.
+    # The 'exit 2' below will be executed if any preceeding command fails.
+    kill -s SIGTERM \$\$ && kill -0 \$\$ || exit 2
+    sleep 1
+    kill -s SIGKILL \$\$
+    exit 3
+) 2>&1 &
+
+exec ./run.exe <$cdir/stdin0 1>$cdir/stdout0 2>$cdir/stderr0
+exit \$?
+EOF
+chmod 755 runit.sh
+
+./runit.sh 2>&1
 ret=$?
-if [ $ret -gt 10 ]; then
+
+if [ $ret -gt 128 ]; then
+  echo "Output unavailable" 1>&2
+  ret=3
+elif [ $ret -gt 10 ]; then
   ret=0
 elif [ "$ret" -ne "0" ]; then
+  echo "Output unavailable" 1>&2
   if [ -f stdout0 ]; then
     tail -n 1 stdout0
   fi
-  exit 10
+  exit 2
 fi
-echo "Collecting time..." >&2
+
+echo "Collecting time..."
 for run in $(seq 1 $nruns); do
   { time -p ./run.exe < stdin0 &> /dev/null ; } 2>&1 | grep real | xargs | cut -d " " -f 2 &>> times.txt
 done
@@ -143,10 +178,7 @@ END {
 	printf "%.6f\n", sum/NR;
 }
 EOF
-echo "Running times:" >&2
-cat times.txt >&2
+echo "Running times:"
+cat times.txt
 
-if [ -f stdout0 ]; then
-  cat stdout0
-fi
 exit $ret
diff --git a/doc/problemexamples/marathon/run/mic b/doc/problemexamples/marathon/run/mic
--- a/doc/problemexamples/marathon/run/mic
+++ b/doc/problemexamples/marathon/run/mic
@@ -112,7 +112,7 @@ cp "$1" run.exe 2>/dev/null
 
 file run.exe | grep -iq "statically linked"
 if [ "$?" != "0" ]; then
-  echo "Warning: $1 is not statically linked" >&2
+  echo "Warning: $1 is not statically linked"
 #  exit 47
 fi
 
@@ -128,36 +128,70 @@ if [ ! -x "$relf" ]; then
 fi
 mchn=`$relf -h run.exe | grep Machine | awk '{print $3}'`
 if [ "$mchn" != "K1OM" ] && [ "$mchn" != "0xb5" ]; then
-  echo "Runtime error: not a Xeon Phi binary"
+  echo "Runtime error: not a Xeon Phi binary compatible."
+  echo "Runtime error: not a Xeon Phi binary compatible." >&2
   exit 2
 fi 
 
-echo "Copying files to mic0" >&2
-scp $sf mic0:/tmp/ 1>&2
-scp run.exe mic0:/tmp 1>&2
-scp stdin0 mic0:/tmp 1>&2
+echo "Copying files to mic0"
+scp $sf mic0:/tmp/
+scp run.exe mic0:/tmp
+scp stdin0 mic0:/tmp
 
 cdir='/tmp'
-echo "Current directory is $cdir -- chrooting on it" >&2
-echo "Running /tmp/$sfexec to check execution" >&2
-echo "cd /tmp ; LD_LIBRARY_PATH=/opt/intel/composerxe/lib/mic/ ./$sfexec -p -a -F10 -f$maxf -r1 -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe ----> NOT WORKING!!!! WHY!?!?!" >&2
+echo "Current directory is $cdir -- chrooting on it"
+echo "Running /tmp/$sfexec to check execution"
+echo "cd /tmp ; LD_LIBRARY_PATH=/opt/intel/composerxe/lib/mic/ ./$sfexec -p -a -F10 -f$maxf -r1 -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe ----> NOT WORKING!!!! WHY!?!?!"
 # ssh mic0 "cd /tmp ; LD_LIBRARY_PATH=/opt/intel/composerxe/lib/mic/ ./$sfexec -p -a -F10 -f$maxf -r1 -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe"
+
+printf -v int_time %.0f "$time"
+time = $((int_time + 1))
+
+cat <<EOF > runit.sh
+#!/bin/bash
+#http://stackoverflow.com/questions/687948/timeout-a-command-in-bash-without-unnecessary-delay
+(
+    ((t = $time))
+
+    while ((t > 0)); do
+        sleep 1
+        kill -0 \$\$ || exit 0
+        ((t -= 1))
+    done
+
+    # Be nice, post SIGTERM first.
+    # The 'exit 2' below will be executed if any preceeding command fails.
+    kill -s SIGTERM \$\$ && kill -0 \$\$ || exit 2
+    sleep 1
+    kill -s SIGKILL \$\$
+    exit 3
+) 2>&1 &
+
 ssh mic0 "LD_LIBRARY_PATH=/opt/intel/composerxe/lib/mic/ /tmp/run.exe < /tmp/stdin0 1> /tmp/stdout0 2> /tmp/stderr0"
+exit \$?
+EOF
+chmod 755 runit.sh
+./runit.sh 2>&1
 ret=$?
 
-echo "Copying files from mic0" >&2
-scp mic0:/tmp/stdout0 . 1>&2
-scp mic0:/tmp/stderr0 . 1>&2
+echo "Copying files from mic0"
+scp mic0:/tmp/stdout0 .
+scp mic0:/tmp/stderr0 .
 
-if [ $ret -gt 10 ]; then
+if [ $ret -gt 128 ]; then
+  echo "Output unavailable" 1>&2
+  ret=3
+elif [ $ret -gt 10 ]; then
   ret=0
 elif [ "$ret" -ne "0" ]; then
+  echo "Output unavailable" 1>&2
   if [ -f stdout0 ]; then
     tail -n 1 stdout0
   fi
-  exit 10
+  exit 2
 fi
-echo "Collecting time..." >&2
+
+echo "Collecting time..."
 for run in $(seq 1 $nruns); do
   { ssh mic0 'LD_LIBRARY_PATH=/opt/intel/composerxe/lib/mic/ time -p /tmp/run.exe < /tmp/stdin0 > /dev/null' ; } 2>&1 | grep real | xargs | cut -d " " -f 2 &>> times.txt
 done
@@ -171,12 +205,9 @@ END {
 	printf "%.6f\n", sum/NR;
 }
 EOF
-echo "Running times:" >&2
-cat times.txt >&2
-echo "Deleting files from mic0" >&2
-ssh mic0 'cd /tmp ; rm run.exe $sfexec std*' 1>&2
+echo "Running times:"
+cat times.txt
+echo "Deleting files from mic0"
+ssh mic0 'cd /tmp ; rm run.exe $sfexec std*'
 
-if [ -f stdout0 ]; then
-  cat stdout0
-fi
 exit $ret
